import type { IntentionId } from "@/lib/intentions";

export type Continent = "europe" | "asia" | "middle_east" | "africa" | "north_america" | "south_america" | "oceania";

export type CuratedCity = {
  slug: string;
  name_pl: string;
  name_en: string;
  name_native?: string;
  country_pl: string;
  country_code: string;
  continent: Continent;
  lat: number;
  lon: number;
  population: number;
  intention_matches: IntentionId[];
  cultural_blurb: string;
  travel_relevance: 1 | 2 | 3 | 4 | 5;
  photo_url: string;
  photo_credit?: string;
  tags: string[];
};

export const CURATED_CITIES: CuratedCity[] = [
  // ─── SPOKÓJ / REGENERACJA ─────────────────────────────────────────────────
  {
    slug: "santorini",
    name_pl: "Santorini", name_en: "Santorini", name_native: "Σαντορίνη",
    country_pl: "Grecja", country_code: "GR", continent: "europe",
    lat: 36.39, lon: 25.46, population: 15000,
    intention_matches: ["spokoj", "milosc", "tworczosc"],
    cultural_blurb: "Wulkaniczna wyspa na Egejskim — biały kamień, granatowy błękit, caldera która kiedyś była górą. Archetyp greckiej ciszy.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1469796466635-455ede028aca?w=800&auto=format&fit=crop&q=80",
    tags: ["beach", "island", "mediterranean", "sunset", "romantic", "iconic"],
  },
  {
    slug: "bali-ubud",
    name_pl: "Bali (Ubud)", name_en: "Bali (Ubud)",
    country_pl: "Indonezja", country_code: "ID", continent: "asia",
    lat: -8.51, lon: 115.26, population: 30000,
    intention_matches: ["spokoj", "duchowosc", "tworczosc"],
    cultural_blurb: "Wewnątrz Bali — ricefieldy, świątynie, rzemieślnicy. Miejsce gdzie joga i medytacja są codziennością, nie weekendem.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&auto=format&fit=crop&q=80",
    tags: ["jungle", "ricefields", "spiritual", "temples", "yoga", "tropical"],
  },
  {
    slug: "sardynia",
    name_pl: "Sardynia", name_en: "Sardinia", name_native: "Sardegna",
    country_pl: "Włochy", country_code: "IT", continent: "europe",
    lat: 40.13, lon: 9.07, population: 1600000,
    intention_matches: ["spokoj", "milosc"],
    cultural_blurb: "Skalista wyspa o tysiącletniej kulturze — nuraghe, owcze stada, turkusowe wody Costa Smeralda. Czas tu biegnie inaczej.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop&q=80",
    tags: ["island", "mediterranean", "beach", "ancient", "nature"],
  },
  {
    slug: "madera",
    name_pl: "Madera", name_en: "Madeira",
    country_pl: "Portugalia", country_code: "PT", continent: "europe",
    lat: 32.65, lon: -16.91, population: 250000,
    intention_matches: ["spokoj", "tworczosc"],
    cultural_blurb: "Atlantycka wyspa kwiatów i levad — nawadniających kanałów biegnących wzdłuż klifów. Łagodny klimat przez cały rok.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80",
    tags: ["island", "atlantic", "nature", "hiking", "flowers"],
  },
  {
    slug: "algarve",
    name_pl: "Algarve", name_en: "Algarve",
    country_pl: "Portugalia", country_code: "PT", continent: "europe",
    lat: 37.09, lon: -8.25, population: 450000,
    intention_matches: ["spokoj", "milosc"],
    cultural_blurb: "Złote klify i oceańskie jaskinie południowej Portugalii. Surferzy rankiem, cisza wieczorem.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1555881400-74d7acaacd47?w=800&auto=format&fit=crop&q=80",
    tags: ["beach", "cliffs", "ocean", "surf", "atlantic"],
  },
  {
    slug: "kreta",
    name_pl: "Kreta", name_en: "Crete", name_native: "Κρήτη",
    country_pl: "Grecja", country_code: "GR", continent: "europe",
    lat: 35.22, lon: 25.02, population: 600000,
    intention_matches: ["spokoj", "duchowosc"],
    cultural_blurb: "Kolebka minojskiej cywilizacji — labirynty, oliwa, wino i góry sięgające 2500 m. Jedno z najstarszych zamieszkałych miejsc Europy.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?w=800&auto=format&fit=crop&q=80",
    tags: ["island", "mediterranean", "ancient", "beach", "mountain"],
  },
  {
    slug: "mauritius",
    name_pl: "Mauritius", name_en: "Mauritius",
    country_pl: "Mauritius", country_code: "MU", continent: "africa",
    lat: -20.29, lon: 57.55, population: 1260000,
    intention_matches: ["spokoj", "milosc"],
    cultural_blurb: "Wyspa-koralowiec na Oceanie Indyjskim — laguny z przezroczystą wodą, wielokulturowa kuchnia, podwodne wodospady piasku.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1589979481223-deb893043163?w=800&auto=format&fit=crop&q=80",
    tags: ["island", "tropical", "beach", "lagoon", "romantic"],
  },
  {
    slug: "nosara",
    name_pl: "Nosara", name_en: "Nosara",
    country_pl: "Kostaryka", country_code: "CR", continent: "north_america",
    lat: 9.98, lon: -85.65, population: 5000,
    intention_matches: ["spokoj", "duchowosc"],
    cultural_blurb: "Jedno z globalnych centrów jogi na wybrzeżu Pacyfiku — dżungla, małpy, betonowe drogi kończące się na złotej plaży.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    tags: ["yoga", "jungle", "beach", "surf", "nature"],
  },
  {
    slug: "tulum",
    name_pl: "Tulum", name_en: "Tulum",
    country_pl: "Meksyk", country_code: "MX", continent: "north_america",
    lat: 20.21, lon: -87.46, population: 35000,
    intention_matches: ["spokoj", "duchowosc", "tworczosc"],
    cultural_blurb: "Ruiny Majów nad Karaibami, cenotes i bohemijska atmosfera. Gdzie starożytność spotyka się z współczesną duchowością.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800&auto=format&fit=crop&q=80",
    tags: ["beach", "ruins", "cenote", "bohemian", "tropical"],
  },
  {
    slug: "essaouira",
    name_pl: "Essaouira", name_en: "Essaouira",
    country_pl: "Maroko", country_code: "MA", continent: "africa",
    lat: 31.51, lon: -9.76, population: 77000,
    intention_matches: ["spokoj", "tworczosc"],
    cultural_blurb: "Atlasowe miasto-forteca na wybrzeżu — wiatr, rybacy, galerie artystów. Jimi Hendrix grał tu na ulicy.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1548813831-8fca679b8b58?w=800&auto=format&fit=crop&q=80",
    tags: ["port", "medina", "artsy", "ocean", "wind", "historic"],
  },
  {
    slug: "sopot",
    name_pl: "Sopot", name_en: "Sopot",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 54.44, lon: 18.56, population: 37000,
    intention_matches: ["spokoj", "milosc"],
    cultural_blurb: "Bałtyckie uzdrowisko z najdłuższym drewnianym molo w Europie. Letnie wieczory z muzyką na Monte Cassino.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1598600517671-9a1f0a012459?w=800&auto=format&fit=crop&q=80",
    tags: ["beach", "baltic", "spa", "pier", "promenade"],
  },
  {
    slug: "kazimierz-dolny",
    name_pl: "Kazimierz Dolny", name_en: "Kazimierz Dolny",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 51.32, lon: 21.95, population: 3500,
    intention_matches: ["spokoj", "tworczosc"],
    cultural_blurb: "Renesansowe miasteczko nad Wisłą — ulubione przez artystów od ponad wieku. Galerie, kurzajki i wapienne wąwozy.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&auto=format&fit=crop&q=80",
    tags: ["historic", "artsy", "river", "renaissance", "village"],
  },

  // ─── MIŁOŚĆ ──────────────────────────────────────────────────────────────
  {
    slug: "paryz",
    name_pl: "Paryż", name_en: "Paris", name_native: "Paris",
    country_pl: "Francja", country_code: "FR", continent: "europe",
    lat: 48.85, lon: 2.35, population: 2200000,
    intention_matches: ["milosc", "tworczosc", "sukces"],
    cultural_blurb: "Miasto światła, kulinarne i artystyczne centrum Europy. Gdzie architektura sama w sobie jest rozmową o pięknie.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1499856845497-7786fec2f843?w=800&auto=format&fit=crop&q=80",
    tags: ["iconic", "romantic", "art", "culture", "architecture", "gastronomy"],
  },
  {
    slug: "wenecja",
    name_pl: "Wenecja", name_en: "Venice", name_native: "Venezia",
    country_pl: "Włochy", country_code: "IT", continent: "europe",
    lat: 45.44, lon: 12.34, population: 260000,
    intention_matches: ["milosc", "tworczosc"],
    cultural_blurb: "Miasto na wodzie — gondole, palazzo, karnawał. Powoli tonie, co nadaje jej niepowtarzalne poczucie przemijania.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1514890547357-a9ee288728a0?w=800&auto=format&fit=crop&q=80",
    tags: ["canals", "romantic", "historic", "art", "gondola", "iconic"],
  },
  {
    slug: "florencja",
    name_pl: "Florencja", name_en: "Florence", name_native: "Firenze",
    country_pl: "Włochy", country_code: "IT", continent: "europe",
    lat: 43.77, lon: 11.25, population: 370000,
    intention_matches: ["milosc", "tworczosc"],
    cultural_blurb: "Kolebka renesansu — Uffizi, David, Ponte Vecchio. Marmurowe piękno zamknięte w ludzkim wymiarze.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1499678567899-3e43d4ef06f7?w=800&auto=format&fit=crop&q=80",
    tags: ["renaissance", "art", "history", "architecture", "romantic"],
  },
  {
    slug: "praga",
    name_pl: "Praga", name_en: "Prague", name_native: "Praha",
    country_pl: "Czechy", country_code: "CZ", continent: "europe",
    lat: 50.08, lon: 14.44, population: 1300000,
    intention_matches: ["milosc", "tworczosc"],
    cultural_blurb: "Gotyckie katedry i barokowe pałace nad Wełtawą. Miasto które przeżyło stulecia i zachowało swój magiczny charakter.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&auto=format&fit=crop&q=80",
    tags: ["gothic", "baroque", "castle", "bridge", "romantic", "beer"],
  },
  {
    slug: "lizbona",
    name_pl: "Lizbona", name_en: "Lisbon", name_native: "Lisboa",
    country_pl: "Portugalia", country_code: "PT", continent: "europe",
    lat: 38.72, lon: -9.14, population: 550000,
    intention_matches: ["milosc", "tworczosc", "transformacja"],
    cultural_blurb: "Miasto na siedmiu wzgórzach — azulejos, fado, tramwaje. Europa z atlantycką duszą i melancholicznym urokiem.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1555881400-74d7acaacd47?w=800&auto=format&fit=crop&q=80",
    tags: ["tram", "fado", "azulejo", "ocean", "hills", "artsy"],
  },
  {
    slug: "charleston",
    name_pl: "Charleston", name_en: "Charleston",
    country_pl: "USA", country_code: "US", continent: "north_america",
    lat: 32.78, lon: -79.93, population: 150000,
    intention_matches: ["milosc"],
    cultural_blurb: "Antebellum mansions i żelazne ogrodzenia nad zatoką — południe USA w swojej najpiękniejszej, cicho melancholicznej formie.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&auto=format&fit=crop&q=80",
    tags: ["southern", "historic", "plantations", "antebellum", "waterfront"],
  },
  {
    slug: "buenos-aires",
    name_pl: "Buenos Aires", name_en: "Buenos Aires",
    country_pl: "Argentyna", country_code: "AR", continent: "south_america",
    lat: -34.60, lon: -58.38, population: 3000000,
    intention_matches: ["milosc", "tworczosc", "transformacja"],
    cultural_blurb: "Paryż Ameryki Południowej — tango, steki, bookstores jako świątynie. Intensywne, piękne i zawsze w kryzysie.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800&auto=format&fit=crop&q=80",
    tags: ["tango", "latin", "architecture", "gastronomy", "culture", "urban"],
  },
  {
    slug: "sevilla",
    name_pl: "Sewilla", name_en: "Seville", name_native: "Sevilla",
    country_pl: "Hiszpania", country_code: "ES", continent: "europe",
    lat: 37.39, lon: -5.99, population: 690000,
    intention_matches: ["milosc", "tworczosc"],
    cultural_blurb: "Flamenco, pomarańcze i mauretańskie ogrody. Miasto gdzie namiętnością żyje się na ulicy, nie w salach.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1559592413-7cbb3c8c7c1c?w=800&auto=format&fit=crop&q=80",
    tags: ["flamenco", "moorish", "orange", "passionate", "historic", "tapas"],
  },
  {
    slug: "wien",
    name_pl: "Wiedeń", name_en: "Vienna", name_native: "Wien",
    country_pl: "Austria", country_code: "AT", continent: "europe",
    lat: 48.21, lon: 16.37, population: 1900000,
    intention_matches: ["milosc", "tworczosc", "sukces"],
    cultural_blurb: "Stolica muzyki i kawiarnianej kultury — Strauss, Klimt, Freud. Imperialne piękno z kafejkową duszą.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1516550135131-c1b5da2bde58?w=800&auto=format&fit=crop&q=80",
    tags: ["imperial", "music", "opera", "cafe", "art", "waltz"],
  },
  {
    slug: "krakow",
    name_pl: "Kraków", name_en: "Krakow",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 50.06, lon: 19.94, population: 800000,
    intention_matches: ["milosc", "duchowosc"],
    cultural_blurb: "Dawna stolica Polski z Wawelem nad Wisłą — gotyk, legendy smoka i żydowski Kazimierz. Historia oddycha tu na każdym rogu.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1562619425-c307bb898d0c?w=800&auto=format&fit=crop&q=80",
    tags: ["castle", "historic", "jewish", "culture", "old-town"],
  },
  {
    slug: "torun",
    name_pl: "Toruń", name_en: "Torun",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 53.01, lon: 18.60, population: 200000,
    intention_matches: ["milosc"],
    cultural_blurb: "Gotyckie miasto urodzenia Kopernika nad Wisłą — pierniki, cegłane mury i delikatna atmosfera zapomnianej stolicy.",
    travel_relevance: 2,
    photo_url: "https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=800&auto=format&fit=crop&q=80",
    tags: ["gothic", "river", "historic", "gingerbread", "copernicus"],
  },

  // ─── SUKCES ───────────────────────────────────────────────────────────────
  {
    slug: "londyn",
    name_pl: "Londyn", name_en: "London",
    country_pl: "Wielka Brytania", country_code: "GB", continent: "europe",
    lat: 51.51, lon: -0.13, population: 9000000,
    intention_matches: ["sukces", "tworczosc"],
    cultural_blurb: "Finansowe i kulturalne centrum świata anglojęzycznego — City, teatry West Endu, muzea za darmo.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80",
    tags: ["finance", "culture", "theatre", "urban", "multicultural", "iconic"],
  },
  {
    slug: "nowy-jork",
    name_pl: "Nowy Jork", name_en: "New York City",
    country_pl: "USA", country_code: "US", continent: "north_america",
    lat: 40.71, lon: -74.01, population: 8300000,
    intention_matches: ["sukces", "tworczosc", "transformacja"],
    cultural_blurb: "Miasto które nie śpi — Broadway, Wall Street, Central Park, pięćdziesiąt języków na jednej ulicy.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=80",
    tags: ["urban", "iconic", "finance", "art", "theatre", "skyscrapers"],
  },
  {
    slug: "singapur",
    name_pl: "Singapur", name_en: "Singapore",
    country_pl: "Singapur", country_code: "SG", continent: "asia",
    lat: 1.35, lon: 103.82, population: 5800000,
    intention_matches: ["sukces"],
    cultural_blurb: "Miasto-kraj z wzorowaną perfekcją — Gardens by the Bay, hawker centres, azjatycki kapitalizm w najczystszej formie.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1525625293386-15f93ec6bfb9?w=800&auto=format&fit=crop&q=80",
    tags: ["finance", "futuristic", "clean", "multicultural", "asian", "modern"],
  },
  {
    slug: "tokio",
    name_pl: "Tokio", name_en: "Tokyo", name_native: "東京",
    country_pl: "Japonia", country_code: "JP", continent: "asia",
    lat: 35.68, lon: 139.69, population: 14000000,
    intention_matches: ["sukces", "tworczosc"],
    cultural_blurb: "Hiper-nowoczesność i tysiącletnia tradycja w jednym rytmie — sushi, manga, świątynie obok wieżowców.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80",
    tags: ["futuristic", "traditional", "sushi", "technology", "anime", "urban"],
  },
  {
    slug: "dubaj",
    name_pl: "Dubaj", name_en: "Dubai",
    country_pl: "ZEA", country_code: "AE", continent: "middle_east",
    lat: 25.21, lon: 55.27, population: 3400000,
    intention_matches: ["sukces"],
    cultural_blurb: "Pustynia zamieniła się w metropolię w ciągu 50 lat — Burj Khalifa, złote souki, sztuczne wyspy.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1512453979798-7c7b9cfe9d99?w=800&auto=format&fit=crop&q=80",
    tags: ["luxury", "skyscrapers", "desert", "modern", "finance", "gold"],
  },
  {
    slug: "mediolan",
    name_pl: "Mediolan", name_en: "Milan", name_native: "Milano",
    country_pl: "Włochy", country_code: "IT", continent: "europe",
    lat: 45.46, lon: 9.19, population: 1400000,
    intention_matches: ["sukces", "tworczosc"],
    cultural_blurb: "Moda, design i finansowa potęga Włoch — Duomo, La Scala, Navigli. Praca i styl jako jedność.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?w=800&auto=format&fit=crop&q=80",
    tags: ["fashion", "design", "finance", "opera", "aperitivo", "urban"],
  },
  {
    slug: "hong-kong",
    name_pl: "Hongkong", name_en: "Hong Kong", name_native: "香港",
    country_pl: "Chiny (SAR)", country_code: "HK", continent: "asia",
    lat: 22.33, lon: 114.17, population: 7500000,
    intention_matches: ["sukces", "transformacja"],
    cultural_blurb: "Gdzie Wschód spotyka Zachód na pionowej linii — wieżowce nad ziołowymi rynkami, tradycja jako wieża w chmurach.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800&auto=format&fit=crop&q=80",
    tags: ["skyline", "urban", "finance", "dim-sum", "night-market", "hybrid"],
  },
  {
    slug: "san-francisco",
    name_pl: "San Francisco", name_en: "San Francisco",
    country_pl: "USA", country_code: "US", continent: "north_america",
    lat: 37.77, lon: -122.42, population: 870000,
    intention_matches: ["sukces", "tworczosc"],
    cultural_blurb: "Silicon Valley, Golden Gate i kontrkultury — miasto które wymyśliło internet i ruchy wolności jednocześnie.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&auto=format&fit=crop&q=80",
    tags: ["tech", "bridge", "fog", "counterculture", "innovation", "bay"],
  },
  {
    slug: "frankfurt",
    name_pl: "Frankfurt", name_en: "Frankfurt",
    country_pl: "Niemcy", country_code: "DE", continent: "europe",
    lat: 50.11, lon: 8.68, population: 760000,
    intention_matches: ["sukces"],
    cultural_blurb: "Finansowe centrum Europy — EBC, wieżowce nad Menem, targi książki i muzea nad rzeką.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&auto=format&fit=crop&q=80",
    tags: ["finance", "banking", "hub", "modern", "trade-fair"],
  },
  {
    slug: "zurych",
    name_pl: "Zurych", name_en: "Zurich", name_native: "Zürich",
    country_pl: "Szwajcaria", country_code: "CH", continent: "europe",
    lat: 47.38, lon: 8.54, population: 430000,
    intention_matches: ["sukces"],
    cultural_blurb: "Miasto z najwyższym jakości życia — jezioro, czyste ulice, szwajcarska precyzja i bankowa dyskrecja.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&auto=format&fit=crop&q=80",
    tags: ["finance", "banking", "clean", "lake", "swiss", "quality-of-life"],
  },
  {
    slug: "warszawa",
    name_pl: "Warszawa", name_en: "Warsaw",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 52.23, lon: 21.01, population: 1800000,
    intention_matches: ["sukces", "transformacja"],
    cultural_blurb: "Stolica zbudowana dwa razy — zrównana z ziemią w 1944, odbudowana z pamięci. Dziś: rosnące miasto startupów.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1562619371-b67725b6fde2?w=800&auto=format&fit=crop&q=80",
    tags: ["finance", "startup", "resilience", "modern", "rebuilt"],
  },
  {
    slug: "berlin",
    name_pl: "Berlin", name_en: "Berlin",
    country_pl: "Niemcy", country_code: "DE", continent: "europe",
    lat: 52.52, lon: 13.40, population: 3700000,
    intention_matches: ["sukces", "tworczosc", "transformacja"],
    cultural_blurb: "Miasto które nigdy nie śpi i nigdy nie skończyło się budować — Mur, techno, galerie w dawnych fabrykach.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&auto=format&fit=crop&q=80",
    tags: ["techno", "art", "history", "wall", "alternative", "creative"],
  },

  // ─── TWÓRCZOŚĆ ────────────────────────────────────────────────────────────
  {
    slug: "brooklyn",
    name_pl: "Brooklyn", name_en: "Brooklyn",
    country_pl: "USA", country_code: "US", continent: "north_america",
    lat: 40.65, lon: -73.95, population: 2600000,
    intention_matches: ["tworczosc"],
    cultural_blurb: "Dzielnica artystów i wynalazców — od Williamsburga do DUMBO, nowe idee rodzą się tu na dwa lata przed Manhattanem.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1483653364400-eedcfb9f1f88?w=800&auto=format&fit=crop&q=80",
    tags: ["artsy", "urban", "creative", "hipster", "bridge", "neighbourhood"],
  },
  {
    slug: "marrakesz",
    name_pl: "Marrakesz", name_en: "Marrakech",
    country_pl: "Maroko", country_code: "MA", continent: "africa",
    lat: 31.63, lon: -8.00, population: 1000000,
    intention_matches: ["tworczosc", "transformacja", "duchowosc"],
    cultural_blurb: "Różowe miasto Maghrebu — souki, riad, minarety i Djemaa el-Fna jako scena wieczna. Wszystko jest piękne i chaotyczne.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1492561104449-bef037f6e9f2?w=800&auto=format&fit=crop&q=80",
    tags: ["medina", "riad", "souk", "spices", "mosaic", "africa"],
  },
  {
    slug: "mexico-city",
    name_pl: "Mexico City", name_en: "Mexico City", name_native: "Ciudad de México",
    country_pl: "Meksyk", country_code: "MX", continent: "north_america",
    lat: 19.43, lon: -99.13, population: 9200000,
    intention_matches: ["tworczosc", "transformacja"],
    cultural_blurb: "Największa metropolia Ameryki Łacińskiej z prekolumbijskim sercem — Frida Kahlo, muralizm i world-class gastronomy.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&auto=format&fit=crop&q=80",
    tags: ["culture", "muralism", "aztec", "gastronomy", "art", "metropolis"],
  },
  {
    slug: "reykjavik",
    name_pl: "Reykjavik", name_en: "Reykjavik",
    country_pl: "Islandia", country_code: "IS", continent: "europe",
    lat: 64.14, lon: -21.94, population: 130000,
    intention_matches: ["tworczosc", "transformacja", "duchowosc"],
    cultural_blurb: "Najmniejsza stolica UE z najwyższą gęstością artystów na głowę — zorza polarna i gejzery jako inspiracja.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1474690455603-a369ec1293f8?w=800&auto=format&fit=crop&q=80",
    tags: ["northern-lights", "geysers", "arctic", "creative", "nature", "minimal"],
  },
  {
    slug: "kioto",
    name_pl: "Kioto", name_en: "Kyoto", name_native: "京都",
    country_pl: "Japonia", country_code: "JP", continent: "asia",
    lat: 35.01, lon: 135.77, population: 1470000,
    intention_matches: ["tworczosc", "duchowosc", "spokoj"],
    cultural_blurb: "Dawna stolica cesarzy — tysiąc świątyń, ogrody zen, gejsze w Gion. Japonia przed Japonią.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop&q=80",
    tags: ["temples", "zen", "geisha", "bamboo", "traditional", "shrines"],
  },
  {
    slug: "wroclaw",
    name_pl: "Wrocław", name_en: "Wroclaw",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 51.11, lon: 17.04, population: 640000,
    intention_matches: ["tworczosc", "transformacja"],
    cultural_blurb: "Miasto czterech kultur — zmieniało granice i narody, wchłaniało każdą zmianę. Dziś: jeden z najbardziej kreatywnych miast Polski.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=800&auto=format&fit=crop&q=80",
    tags: ["historic", "multicultural", "bridge", "creative", "resilience"],
  },
  {
    slug: "lodz",
    name_pl: "Łódź", name_en: "Lodz",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 51.76, lon: 19.46, population: 670000,
    intention_matches: ["tworczosc"],
    cultural_blurb: "Miasto filmowe i street-artowe — dawne fabryki włókiennicze zamienione w galerie. Manufaktura, Piotrkowska, nowa fala.",
    travel_relevance: 2,
    photo_url: "https://images.unsplash.com/photo-1571757767119-68b8dbed8c97?w=800&auto=format&fit=crop&q=80",
    tags: ["street-art", "film", "industrial", "factories", "creative", "alternative"],
  },
  {
    slug: "tbilisi",
    name_pl: "Tbilisi", name_en: "Tbilisi", name_native: "თბილისი",
    country_pl: "Gruzja", country_code: "GE", continent: "asia",
    lat: 41.69, lon: 44.83, population: 1100000,
    intention_matches: ["tworczosc", "transformacja"],
    cultural_blurb: "Wschód i Zachód w jednym mieście — balkony z drewnianymi rzeźbieniami, polyphoniczne śpiewy i wino jako rytuał.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1564414368508-59e6e1b9c5d4?w=800&auto=format&fit=crop&q=80",
    tags: ["wine", "balcony", "crossroads", "orthodox", "artsy", "food"],
  },

  // ─── DUCHOWOŚĆ ───────────────────────────────────────────────────────────
  {
    slug: "varanasi",
    name_pl: "Varanasi", name_en: "Varanasi",
    country_pl: "Indie", country_code: "IN", continent: "asia",
    lat: 25.32, lon: 82.98, population: 1500000,
    intention_matches: ["duchowosc"],
    cultural_blurb: "Najstarsze zamieszkałe miasto świata nad Gangesem — ghaty, kremacje, mantry o świcie. Granica między życiem a śmiercią.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1561361058-c24e014f2e85?w=800&auto=format&fit=crop&q=80",
    tags: ["ganges", "ghat", "pilgrimage", "ancient", "sacred", "hinduism"],
  },
  {
    slug: "sedona",
    name_pl: "Sedona", name_en: "Sedona",
    country_pl: "USA", country_code: "US", continent: "north_america",
    lat: 34.87, lon: -111.76, population: 10000,
    intention_matches: ["duchowosc"],
    cultural_blurb: "Czerwone skalne formacje Arizony znane z vortex energetycznych — miejsce pielgrzymek dla poszukujących.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
    tags: ["vortex", "red-rock", "spiritual", "desert", "new-age", "nature"],
  },
  {
    slug: "machu-picchu",
    name_pl: "Machu Picchu", name_en: "Machu Picchu",
    country_pl: "Peru", country_code: "PE", continent: "south_america",
    lat: -13.16, lon: -72.54, population: 1000,
    intention_matches: ["duchowosc", "transformacja"],
    cultural_blurb: "Inkaskie miasto w chmurach — zbudowane z kamienia bez zaprawy murarskiej, zapomniane przez 400 lat.",
    travel_relevance: 5,
    photo_url: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&auto=format&fit=crop&q=80",
    tags: ["inca", "ruins", "mountain", "sacred", "cloud", "ancient"],
  },
  {
    slug: "thimphu",
    name_pl: "Thimphu", name_en: "Thimphu",
    country_pl: "Bhutan", country_code: "BT", continent: "asia",
    lat: 27.47, lon: 89.64, population: 115000,
    intention_matches: ["duchowosc", "spokoj"],
    cultural_blurb: "Stolica jedynego kraju mierzącego Gross National Happiness — dzong, mnisi i Himalaje za każdym rogiem.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop&q=80",
    tags: ["himalaya", "buddhism", "happiness", "monks", "dzong", "sustainable"],
  },
  {
    slug: "jerozolima",
    name_pl: "Jerozolima", name_en: "Jerusalem", name_native: "ירושלים",
    country_pl: "Izrael", country_code: "IL", continent: "middle_east",
    lat: 31.77, lon: 35.21, population: 970000,
    intention_matches: ["duchowosc"],
    cultural_blurb: "Święte Miasto trzech monoteizmów — Ściana Płaczu, Kościół Grobu Świętego, Meczet Al-Aksa. Kamień nasączony modlitwami.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1552422535-c45813c61732?w=800&auto=format&fit=crop&q=80",
    tags: ["pilgrimage", "three-religions", "ancient", "sacred", "old-city"],
  },
  {
    slug: "glastonbury",
    name_pl: "Glastonbury", name_en: "Glastonbury",
    country_pl: "Wielka Brytania", country_code: "GB", continent: "europe",
    lat: 51.15, lon: -2.72, population: 9000,
    intention_matches: ["duchowosc"],
    cultural_blurb: "Legendarny Avalon arthuriańskich legend — Tor, opactwo, kryształy i doroczny festiwal jako misterium.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1580656392619-1e7e16bd6e36?w=800&auto=format&fit=crop&q=80",
    tags: ["arthurian", "tor", "festival", "new-age", "sacred", "legend"],
  },
  {
    slug: "czestochowa",
    name_pl: "Częstochowa", name_en: "Czestochowa",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 50.81, lon: 19.12, population: 220000,
    intention_matches: ["duchowosc"],
    cultural_blurb: "Polska Lourdes — Jasna Góra z Czarną Madonną przyciąga miliony pielgrzymów rocznie.",
    travel_relevance: 2,
    photo_url: "https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=800&auto=format&fit=crop&q=80",
    tags: ["pilgrimage", "black-madonna", "monastery", "catholic", "polish"],
  },
  {
    slug: "kalwaria-zebrzydowska",
    name_pl: "Kalwaria Zebrzydowska", name_en: "Kalwaria Zebrzydowska",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 49.87, lon: 19.68, population: 5000,
    intention_matches: ["duchowosc"],
    cultural_blurb: "Barokowy zespół kościołów i kaplic na wzgórzach — droga krzyżowa rozłożona na kilometrach pejzażu. UNESCO.",
    travel_relevance: 2,
    photo_url: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800&auto=format&fit=crop&q=80",
    tags: ["pilgrimage", "unesco", "baroque", "stations-of-cross", "mountains"],
  },

  // ─── TRANSFORMACJA ────────────────────────────────────────────────────────
  {
    slug: "cape-town",
    name_pl: "Kapsztad", name_en: "Cape Town",
    country_pl: "RPA", country_code: "ZA", continent: "africa",
    lat: -33.93, lon: 18.42, population: 4600000,
    intention_matches: ["transformacja", "tworczosc"],
    cultural_blurb: "Góra Stołowa nad Atlantykiem — gdzie kończyły się mapy i zaczynał nowy świat. Post-apartheid, tętniące życiem.",
    travel_relevance: 4,
    photo_url: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&auto=format&fit=crop&q=80",
    tags: ["table-mountain", "ocean", "wine", "post-apartheid", "diverse"],
  },
  {
    slug: "beirut",
    name_pl: "Bejrut", name_en: "Beirut", name_native: "بيروت",
    country_pl: "Liban", country_code: "LB", continent: "middle_east",
    lat: 33.89, lon: 35.50, population: 2200000,
    intention_matches: ["transformacja"],
    cultural_blurb: "Paryż Bliskiego Wschodu który przeżył wojnę domową i eksplozję — rebuilding as act of defiance.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1558181402-2fea7a5ddeb7?w=800&auto=format&fit=crop&q=80",
    tags: ["resilience", "food", "nightlife", "mediterranean", "rebuilt", "culture"],
  },
  {
    slug: "detroit",
    name_pl: "Detroit", name_en: "Detroit",
    country_pl: "USA", country_code: "US", continent: "north_america",
    lat: 42.33, lon: -83.05, population: 640000,
    intention_matches: ["transformacja", "tworczosc"],
    cultural_blurb: "Motor City w trakcie renesansu — abandoned skyscrapers, techno music birthplace, urban farms w ruinach.",
    travel_relevance: 2,
    photo_url: "https://images.unsplash.com/photo-1609813041659-a5f9f1a4b62e?w=800&auto=format&fit=crop&q=80",
    tags: ["resilience", "techno", "decay-beauty", "urban-renewal", "art"],
  },
  {
    slug: "belfast",
    name_pl: "Belfast", name_en: "Belfast",
    country_pl: "Wielka Brytania", country_code: "GB", continent: "europe",
    lat: 54.60, lon: -5.93, population: 340000,
    intention_matches: ["transformacja"],
    cultural_blurb: "Miasto murali pokoju — dawny konflikt zamieniony w narrację pojednania. Titanic Museum, peace walls i ciemne piwo.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    tags: ["murals", "peace", "titanic", "resilience", "pub", "northern-ireland"],
  },
  {
    slug: "sarajewo",
    name_pl: "Sarajewo", name_en: "Sarajevo", name_native: "Sarajevo",
    country_pl: "Bośnia", country_code: "BA", continent: "europe",
    lat: 43.85, lon: 18.41, population: 420000,
    intention_matches: ["transformacja"],
    cultural_blurb: "Miasto gdzie trzy religie żyją obok siebie — meczet, kościół, synagoga przy jednej ulicy. Oblężenie, odrodzenie.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1549451371-64aa98a6f660?w=800&auto=format&fit=crop&q=80",
    tags: ["three-cultures", "ottoman", "balkans", "resilience", "history"],
  },
  {
    slug: "kijow",
    name_pl: "Kijów", name_en: "Kyiv", name_native: "Київ",
    country_pl: "Ukraina", country_code: "UA", continent: "europe",
    lat: 50.45, lon: 30.52, population: 3000000,
    intention_matches: ["transformacja"],
    cultural_blurb: "Matka miast Rusi Kijowskiej, dziś symbol oporu — złote kopuły nad Dnieprem i siła narodu budującego swoją tożsamość.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1568174464592-cec73f0d1e00?w=800&auto=format&fit=crop&q=80",
    tags: ["golden-domes", "slavic", "resilience", "history", "dnieper"],
  },
  {
    slug: "gdansk",
    name_pl: "Gdańsk", name_en: "Gdansk",
    country_pl: "Polska", country_code: "PL", continent: "europe",
    lat: 54.35, lon: 18.65, population: 490000,
    intention_matches: ["transformacja", "milosc"],
    cultural_blurb: "Hanzeatyckie miasto nad Bałtykiem, kolebka Solidarności — bursztyn, gotyk i stocznia która zmieniła Europę.",
    travel_relevance: 3,
    photo_url: "https://images.unsplash.com/photo-1571104508999-893933ded431?w=800&auto=format&fit=crop&q=80",
    tags: ["hanseatic", "amber", "solidarity", "baltic", "gothic", "resilience"],
  },
];

export function getCuratedCity(slug: string): CuratedCity | undefined {
  return CURATED_CITIES.find((c) => c.slug === slug);
}

export function getCitiesForIntention(intentionId: string): CuratedCity[] {
  return CURATED_CITIES.filter((c) => c.intention_matches.includes(intentionId as IntentionId));
}
